### ISSUE TITLE
Permissions based on Slack groups

### ISSUE THREAD

**Issue by mattouille** [gopherworks/bawt#14]
## Expected Behavior

Each plugin will have an optional field of `RequiredGroups` and `ExcludedGroups`. 

Each listener will have an optional field of `RequiredGroups` and `ExcludedGroups`. 

A list of Global Admins in the config:

```yaml
Slack:
    slack_admins_are_admins: true
    global_admins:
        - user1
        - user2
        ...
```
These admins cannot be deleted.

All other users should be derived from Slack Groups. Users that are identified as "Admin" on Slack will automatically receive admin privileges on core Bawt functionality. Plugins and listeners can whitelist and blacklist as they choose.

## Current Behavior

N/A

## Possible Solution

- https://api.slack.com/methods/groups.list
- https://godoc.org/github.com/nlopes/slack#Client.GetGroups
- Each plugin will have an optional field
- https://github.com/nlopes/slack/blob/master/usergroups.go#L222-L224
